namespace ConectaMentes.Domain.Entities;

public enum SkillType { Domina, NecesitaApoyo }
public enum RequestStatus { Abierta, ConCoincidencias, Conectada, Cerrada, Cancelada }
public enum MatchStatus { Sugerida, Rechazada, Aceptada }
public enum ConnectionStatus { PendienteColaborador, Activa, Rechazada, Cancelada }
public enum SessionStatus { Agendada, Completada, Cancelada }
public enum ReportStatus { Abierto, EnRevision, Resuelto }
public enum TutorPlan { Free, Premium }
public enum SubscriptionStatus { Active, Trialing, Canceled, Expired }
public enum TutorMessageRole { User, Assistant }
public enum TutorSafetyStatus { Clear, Redirected }

public sealed class SkillProfile { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Topic { get; set; } = ""; public SkillType Type { get; set; } public int Confidence { get; set; } public bool Visible { get; set; } = true; }
public sealed class Availability { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string TimeSlots { get; set; } = ""; public string PreferredMode { get; set; } = "ambas"; }
public sealed class SupportRequest { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Topic { get; set; } = ""; public string Description { get; set; } = ""; public string HelpType { get; set; } = ""; public string DesiredSchedule { get; set; } = ""; public RequestStatus Status { get; set; } = RequestStatus.Abierta; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class SupportRequestComment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid RequestId { get; set; } public Guid AuthorId { get; set; } public string Text { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Match { public Guid Id { get; set; } = Guid.NewGuid(); public Guid RequestId { get; set; } public Guid CandidateUserId { get; set; } public decimal Score { get; set; } public string Explanation { get; set; } = ""; public MatchStatus Status { get; set; } = MatchStatus.Sugerida; public DateTimeOffset CalculatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Connection { public Guid Id { get; set; } = Guid.NewGuid(); public Guid? RequestId { get; set; } public Guid? MatchId { get; set; } public Guid RequesterId { get; set; } public Guid CollaboratorId { get; set; } public ConnectionStatus Status { get; set; } = ConnectionStatus.PendienteColaborador; }
public sealed class LearningSession { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ConnectionId { get; set; } public DateTimeOffset Date { get; set; } public int DurationMinutes { get; set; } public string Mode { get; set; } = "virtual"; public string Objective { get; set; } = ""; public string Guide { get; set; } = ""; public string? MeetUrl { get; set; } public string? GoogleCalendarEventId { get; set; } public SessionStatus Status { get; set; } = SessionStatus.Agendada; }
public sealed class Rating { public Guid Id { get; set; } = Guid.NewGuid(); public Guid? SessionId { get; set; } public Guid? ConnectionId { get; set; } public Guid AuthorId { get; set; } public Guid EvaluatedUserId { get; set; } public int Usefulness { get; set; } public int Respect { get; set; } public int Fulfillment { get; set; } public int Clarity { get; set; } public string Comment { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Recognition { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Type { get; set; } = "insignia"; public string CriterionOrigin { get; set; } = ""; public DateTimeOffset GrantedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Block { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public Guid BlockedUserId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Report { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AuthorId { get; set; } public Guid ReportedUserId { get; set; } public Guid ReferenceId { get; set; } public string Reason { get; set; } = ""; public string Description { get; set; } = ""; public ReportStatus Status { get; set; } = ReportStatus.Abierto; public string ResolutionNote { get; set; } = ""; public Guid? ModeratorId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ReportEvidence { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ReportId { get; set; } public string FileName { get; set; } = ""; public string StoredName { get; set; } = ""; public string ContentType { get; set; } = "application/octet-stream"; public long SizeBytes { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Notification { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Type { get; set; } = "general"; public string Title { get; set; } = ""; public string Body { get; set; } = ""; public Guid? ReferenceId { get; set; } public bool IsRead { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PushSubscriptionRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string EndpointHash { get; set; } = ""; public string Endpoint { get; set; } = ""; public string P256dh { get; set; } = ""; public string Auth { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ChatMessage { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ConnectionId { get; set; } public Guid SenderId { get; set; } public string Text { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ChatAttachment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid MessageId { get; set; } public Guid ConnectionId { get; set; } public Guid SenderId { get; set; } public string FileName { get; set; } = ""; public string StoredName { get; set; } = ""; public string ContentType { get; set; } = "application/octet-stream"; public long SizeBytes { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TutorConversation { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Subject { get; set; } = "General"; public string Title { get; set; } = "Nueva conversación"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset LastActivityAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TutorMessage { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ConversationId { get; set; } public TutorMessageRole Role { get; set; } public string Content { get; set; } = ""; public string Mode { get; set; } = "explicar"; public TutorSafetyStatus SafetyStatus { get; set; } = TutorSafetyStatus.Clear; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TutorUsage { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public DateTime PeriodStart { get; set; } public int MessagesUsed { get; set; } public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Subscription { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public TutorPlan Plan { get; set; } = TutorPlan.Free; public SubscriptionStatus Status { get; set; } = SubscriptionStatus.Active; public string Provider { get; set; } = "internal"; public string? ExternalSubscriptionId { get; set; } public DateTimeOffset StartedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? ExpiresAt { get; set; } }
