namespace ConectaMentes.Domain.Entities;

public enum SkillType { Domina, NecesitaApoyo }
public enum RequestStatus { Abierta, ConCoincidencias, Conectada, Cerrada, Cancelada }
public enum MatchStatus { Sugerida, Rechazada, Aceptada }
public enum ConnectionStatus { PendienteColaborador, Activa, Rechazada }
public enum SessionStatus { Agendada, Completada, Cancelada }
public enum ReportStatus { Abierto, EnRevision, Resuelto }

public sealed class SkillProfile { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Topic { get; set; } = ""; public SkillType Type { get; set; } public int Confidence { get; set; } public bool Visible { get; set; } = true; }
public sealed class Availability { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string TimeSlots { get; set; } = ""; public string PreferredMode { get; set; } = "ambas"; }
public sealed class SupportRequest { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Topic { get; set; } = ""; public string Description { get; set; } = ""; public string HelpType { get; set; } = ""; public string DesiredSchedule { get; set; } = ""; public RequestStatus Status { get; set; } = RequestStatus.Abierta; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Match { public Guid Id { get; set; } = Guid.NewGuid(); public Guid RequestId { get; set; } public Guid CandidateUserId { get; set; } public decimal Score { get; set; } public string Explanation { get; set; } = ""; public MatchStatus Status { get; set; } = MatchStatus.Sugerida; public DateTimeOffset CalculatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Connection { public Guid Id { get; set; } = Guid.NewGuid(); public Guid RequestId { get; set; } public Guid MatchId { get; set; } public Guid RequesterId { get; set; } public Guid CollaboratorId { get; set; } public ConnectionStatus Status { get; set; } = ConnectionStatus.PendienteColaborador; }
public sealed class LearningSession { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ConnectionId { get; set; } public DateTimeOffset Date { get; set; } public int DurationMinutes { get; set; } public string Mode { get; set; } = "virtual"; public string Objective { get; set; } = ""; public string Guide { get; set; } = ""; public SessionStatus Status { get; set; } = SessionStatus.Agendada; }
public sealed class Rating { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SessionId { get; set; } public Guid AuthorId { get; set; } public Guid EvaluatedUserId { get; set; } public int Usefulness { get; set; } public int Respect { get; set; } public int Fulfillment { get; set; } public int Clarity { get; set; } public string Comment { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Recognition { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string Type { get; set; } = "insignia"; public string CriterionOrigin { get; set; } = ""; public DateTimeOffset GrantedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Block { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public Guid BlockedUserId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Report { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AuthorId { get; set; } public Guid ReportedUserId { get; set; } public Guid ReferenceId { get; set; } public string Reason { get; set; } = ""; public string Description { get; set; } = ""; public ReportStatus Status { get; set; } = ReportStatus.Abierto; public string ResolutionNote { get; set; } = ""; public Guid? ModeratorId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
