import { FormEvent, StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8080';
type Mode = 'welcome' | 'login' | 'register' | 'recover';
type Tab = 'inicio' | 'perfil' | 'solicitudes' | 'coincidencias' | 'agenda' | 'seguridad' | 'panel';

async function api(path: string, options: RequestInit = {}) {
  const token = localStorage.getItem('conectamente_token');
  const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...options.headers } });
  if (!response.ok) throw new Error(response.status === 401 ? 'Tu sesión ha expirado.' : 'No pudimos completar esta acción.');
  return response.status === 204 ? null : response.json();
}

function App() {
  const [mode, setMode] = useState<Mode>(localStorage.getItem('conectamente_token') ? 'welcome' : 'welcome');
  const [tab, setTab] = useState<Tab>('inicio');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [me, setMe] = useState<any>(null);
  const [requests, setRequests] = useState<any[]>([]);
  const [matches, setMatches] = useState<any[]>([]);
  const [selectedRequest, setSelectedRequest] = useState('');
  const [profile, setProfile] = useState<any>({ habilidades: [], disponibilidad: null });
  const [requestForm, setRequestForm] = useState({ topic: '', description: '', helpType: 'comprender', desiredSchedule: '' });

  const logged = Boolean(localStorage.getItem('conectamente_token'));
  useEffect(() => { if (logged) { api('/api/usuarios/me').then(setMe).catch(() => localStorage.removeItem('conectamente_token')); } }, [logged]);
  useEffect(() => { if (logged && tab === 'perfil') api('/api/perfil').then(setProfile).catch(showError); if (logged && tab === 'solicitudes') api('/api/solicitudes/mias').then(setRequests).catch(showError); }, [logged, tab]);
  function showError(error: unknown) { setNotice(error instanceof Error ? error.message : 'Ocurrió un error.'); }

  async function authSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setNotice('');
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const path = mode === 'login' ? '/api/auth/login' : mode === 'register' ? '/api/auth/registro' : '/api/auth/recuperar-contrasena';
    try { const result = await api(path, { method: 'POST', body: JSON.stringify(data) }); if (result?.accessToken) { localStorage.setItem('conectamente_token', result.accessToken); setMe(result.user); setMode('welcome'); } else setNotice('Si los datos son válidos, recibirás instrucciones para continuar.'); } catch (e) { showError(e); } finally { setBusy(false); }
  }
  async function createRequest(event: FormEvent) { event.preventDefault(); try { await api('/api/solicitudes', { method: 'POST', body: JSON.stringify(requestForm) }); setRequestForm({ topic: '', description: '', helpType: 'comprender', desiredSchedule: '' }); setNotice('Solicitud publicada. Ya puede encontrar coincidencias.'); setRequests(await api('/api/solicitudes/mias')); } catch (e) { showError(e); } }
  async function calculate(requestId: string) { try { await api('/api/solicitudes/' + requestId + '/calcular-coincidencias', { method: 'POST' }); setSelectedRequest(requestId); setMatches(await api('/api/solicitudes/' + requestId + '/coincidencias')); setTab('coincidencias'); setNotice('Coincidencias calculadas con reglas explicables.'); } catch (e) { showError(e); } }

  if (!logged) return <Welcome mode={mode} setMode={setMode} notice={notice} busy={busy} submit={authSubmit} />;
  return <main className="app-shell dashboard"><header className="topbar"><div><p className="eyebrow">CONEXIONES QUE ENSEÑAN</p><h1>Hola, {me?.displayName ?? 'estudiante'}</h1></div><button className="text-button" onClick={() => { localStorage.removeItem('conectamente_token'); location.reload(); }}>Cerrar sesión</button></header><nav className="tabs" aria-label="Secciones">{(['inicio', 'perfil', 'solicitudes', 'coincidencias', 'agenda', 'seguridad', 'panel'] as Tab[]).map(item => <button className={tab === item ? 'tab active' : 'tab'} key={item} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>{notice && <p className="toast" role="status">{notice}</p>}{tab === 'inicio' && <section className="dashboard-grid"><article className="feature-card"><p className="eyebrow">TU PRÓXIMO PASO</p><h2>Completa tu perfil de aprendizaje</h2><p>Cuéntanos qué dominas y qué quieres aprender para encontrar mejores conexiones.</p><button className="button button-primary" onClick={() => setTab('perfil')}>Ir a mi perfil</button></article><article className="status-card"><div className="status-dot" /><div><p className="eyebrow">PRIVACIDAD</p><h2>Tú decides qué compartir</h2><p>Solo usamos la información necesaria para conectar estudiantes.</p></div></article></section>}{tab === 'perfil' && <Profile profile={profile} setProfile={setProfile} notify={setNotice} />} {tab === 'solicitudes' && <section><div className="section-heading"><div><p className="eyebrow">APOYO ACADÉMICO</p><h2>Mis solicitudes</h2></div></div><form className="form-card compact-form" onSubmit={createRequest}><label>Tema<input value={requestForm.topic} onChange={e => setRequestForm({ ...requestForm, topic: e.target.value })} required /></label><label>¿En qué necesitas apoyo?<textarea value={requestForm.description} onChange={e => setRequestForm({ ...requestForm, description: e.target.value })} required /></label><label>Horario deseado<input value={requestForm.desiredSchedule} onChange={e => setRequestForm({ ...requestForm, desiredSchedule: e.target.value })} /></label><button className="button button-primary" type="submit">Publicar solicitud</button></form><div className="list">{requests.map(item => <article className="list-item" key={item.id}><div><strong>{item.topic}</strong><p>{item.description}</p></div><div><span className="tag">{item.status}</span><button className="text-button" onClick={() => calculate(item.id)}>Buscar compañeros</button></div></article>)}</div></section>}{tab === 'coincidencias' && <Matches matches={matches} requestId={selectedRequest} notify={setNotice} />} {tab === 'agenda' && <Agenda notify={setNotice} />} {tab === 'seguridad' && <Security notify={setNotice} />} {tab === 'panel' && <Empty title="Panel institucional" text="Este panel está protegido para roles de coordinación y moderación; sus datos siempre se entregan agregados." />}</main>;
}

function Welcome({ mode, setMode, notice, busy, submit }: any) { if (mode === 'welcome') return <main className="app-shell"><section className="hero"><p className="eyebrow">CONEXIONES QUE ENSEÑAN</p><h1>ConectaMentes <em>IA</em></h1><p className="lead">Encuentra apoyo académico entre compañeros que comparten tus objetivos.</p><div className="actions"><button className="button button-primary" onClick={() => setMode('register')}>Crear una cuenta</button><button className="button button-secondary" onClick={() => setMode('login')}>Iniciar sesión</button></div></section><section className="status-card"><div className="status-dot" /><div><p className="eyebrow">APRENDER EN COMUNIDAD</p><h2>Una duda puede convertirse en una conexión</h2><p>Comparte lo que necesitas y también lo que sabes.</p></div></section></main>; const register = mode === 'register'; return <main className="app-shell form-shell"><button className="back-link" onClick={() => setMode('welcome')}>← Volver</button><section className="form-card"><p className="eyebrow">CONFIANZA Y PRIVACIDAD</p><h1>{register ? 'Crear una cuenta' : mode === 'login' ? 'Qué bueno verte' : 'Recuperar acceso'}</h1><form onSubmit={submit}>{register && <><label>Nombre o alias<input name="displayName" required /></label><label>Carrera<input name="career" required /></label><label>Periodo académico<input name="academicTerm" required /></label></>}<label>Email<input name="email" type="email" required /></label>{mode !== 'recover' && <label>Contraseña<input name="password" type="password" minLength={8} required /></label>}<button className="button button-primary full-width" disabled={busy}>{busy ? 'Procesando…' : register ? 'Crear cuenta' : mode === 'login' ? 'Entrar' : 'Solicitar recuperación'}</button></form>{notice && <p className="toast" role="alert">{notice}</p>}{mode === 'login' && <button className="text-button" onClick={() => setMode('recover')}>¿Olvidaste tu contraseña?</button>}</section></main>; }
function Profile({ profile, setProfile, notify }: any) { const [skill, setSkill] = useState({ topic: '', type: 'Domina', confidence: 4, visible: true }); async function add(event: FormEvent) { event.preventDefault(); try { await api('/api/perfil/habilidades', { method: 'POST', body: JSON.stringify({ ...skill, confidence: Number(skill.confidence) }) }); setProfile(await api('/api/perfil')); setSkill({ ...skill, topic: '' }); notify('Tema agregado a tu perfil.'); } catch (e) { notify(e instanceof Error ? e.message : 'No pudimos guardar el tema.'); } } return <section><p className="eyebrow">MI APRENDIZAJE</p><h2>Perfil de habilidades</h2><form className="form-card compact-form" onSubmit={add}><label>Tema<input value={skill.topic} onChange={e => setSkill({ ...skill, topic: e.target.value })} required /></label><label>Tipo<select value={skill.type} onChange={e => setSkill({ ...skill, type: e.target.value })}><option value="Domina">Lo domino</option><option value="NecesitaApoyo">Necesito apoyo</option></select></label><label>Nivel de confianza<input type="range" min="1" max="5" value={skill.confidence} onChange={e => setSkill({ ...skill, confidence: Number(e.target.value) })} /></label><button className="button button-primary">Agregar tema</button></form><div className="chips">{profile.habilidades?.map((item: any) => <span className="chip" key={item.id}>{item.topic} · {item.type === 'Domina' || item.type === 0 ? 'domino' : 'necesito apoyo'}</span>)}</div></section>; }
function Matches({ matches, requestId, notify }: any) { async function accept(id: string) { try { await api('/api/coincidencias/' + id + '/aceptar', { method: 'POST' }); notify('Conexión propuesta. Falta la aceptación del colaborador.'); } catch (e) { notify(e instanceof Error ? e.message : 'No pudimos aceptar la coincidencia.'); } } async function reject(id: string) { try { await api('/api/coincidencias/' + id + '/rechazar', { method: 'POST' }); notify('Recomendación rechazada sin penalización.'); } catch (e) { notify(e instanceof Error ? e.message : 'No pudimos rechazar la coincidencia.'); } } return <section><p className="eyebrow">COMPATIBILIDAD EXPLICABLE</p><h2>Compañeros recomendados</h2>{!requestId || matches.length === 0 ? <Empty title="Aún no hay coincidencias" text="Publica una solicitud y calcula candidatos para ver recomendaciones." /> : <div className="list">{matches.map((item: any) => <article className="list-item" key={item.id}><div><strong>{item.candidate}</strong><p>{item.explanation}</p><span className="tag">{Math.round(item.score)}% compatible</span></div><div className="actions-inline"><button className="button button-primary" onClick={() => accept(item.id)}>Aceptar</button><button className="button button-secondary" onClick={() => reject(item.id)}>Rechazar</button></div></article>)}</div>}</section>; }
function Agenda({ notify }: any) { const [form, setForm] = useState({ connectionId: '', date: '', durationMinutes: 30, mode: 'virtual', objective: '' }); async function submit(event: FormEvent) { event.preventDefault(); try { await api('/api/conexiones/' + form.connectionId + '/sesiones', { method: 'POST', body: JSON.stringify({ ...form, durationMinutes: Number(form.durationMinutes), date: new Date(form.date).toISOString() }) }); notify('Sesión propuesta con una guía inicial.'); } catch (e) { notify(e instanceof Error ? e.message : 'No pudimos agendar la sesión.'); } } return <section><p className="eyebrow">COORDINACIÓN</p><h2>Agendar una sesión</h2><form className="form-card compact-form" onSubmit={submit}><label>ID de conexión<input value={form.connectionId} onChange={e => setForm({ ...form, connectionId: e.target.value })} required /></label><label>Fecha y hora<input type="datetime-local" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} required /></label><label>Duración<select value={form.durationMinutes} onChange={e => setForm({ ...form, durationMinutes: Number(e.target.value) })}><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option></select></label><label>Objetivo<input value={form.objective} onChange={e => setForm({ ...form, objective: e.target.value })} required /></label><button className="button button-primary">Proponer sesión</button></form></section>; }
function Security({ notify }: any) { const [form, setForm] = useState({ reportedUserId: '', referenceId: '', reason: '', description: '' }); async function submit(event: FormEvent) { event.preventDefault(); try { await api('/api/reportes', { method: 'POST', body: JSON.stringify(form) }); setForm({ reportedUserId: '', referenceId: '', reason: '', description: '' }); notify('Reporte recibido. Un moderador humano lo revisará.'); } catch (e) { notify(e instanceof Error ? e.message : 'No pudimos enviar el reporte.'); } } return <section><p className="eyebrow">CONFIANZA Y CUIDADO</p><h2>Reportar una situación</h2><form className="form-card compact-form" onSubmit={submit}><label>ID de usuario reportado<input value={form.reportedUserId} onChange={e => setForm({ ...form, reportedUserId: e.target.value })} required /></label><label>ID de sesión o conexión<input value={form.referenceId} onChange={e => setForm({ ...form, referenceId: e.target.value })} required /></label><label>Motivo<input value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} required /></label><label>Descripción<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} required /></label><button className="button button-primary">Enviar a moderación</button></form></section>; }
function Empty({ title, text }: { title: string; text: string }) { return <section className="empty"><p className="eyebrow">PRÓXIMAMENTE EN TU FLUJO</p><h2>{title}</h2><p>{text}</p></section>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));
