const DO_LOCALE = 'es-DO';
const DO_TIME_ZONE = 'America/Santo_Domingo';

export function dominicanDateKey(isoDate: string | Date) { return new Date(isoDate).toLocaleDateString('es-DO', { timeZone: 'America/Santo_Domingo', year: 'numeric', month: '2-digit', day: '2-digit' }); }
export function formatChatDayDivider(isoDate: string | Date) { const d = new Date(isoDate); const today = new Date(); const isToday = d.getDate() === today.getDate() && d.getMonth() === today.getMonth() && d.getFullYear() === today.getFullYear(); return isToday ? 'Hoy' : d.toLocaleDateString('es-DO', { timeZone: 'America/Santo_Domingo', weekday: 'long', day: 'numeric', month: 'long' }); }
export function formatDominicanTime(value: string | Date) { return new Intl.DateTimeFormat(DO_LOCALE, { timeZone: DO_TIME_ZONE, hour: 'numeric', minute: '2-digit', hour12: true }).format(new Date(value)); }
export function formatRelative(isoDate: string) { const now = new Date(); const d = new Date(isoDate); const diffMin = Math.floor((now.getTime() - d.getTime()) / 60000); if (diffMin < 1) return 'ahora'; if (diffMin < 60) return `${diffMin} min`; const diffHrs = Math.floor(diffMin / 60); if (diffHrs < 24) return `${diffHrs} h`; const diffDays = Math.floor(diffHrs / 24); if (diffDays < 7) return `${diffDays} d`; return d.toLocaleDateString('es-DO'); }
export function formatDominicanDate(value: string | Date) { return new Intl.DateTimeFormat(DO_LOCALE, { timeZone: DO_TIME_ZONE, day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
export function formatDominicanDateLong(value: string | Date) { return new Intl.DateTimeFormat(DO_LOCALE, { timeZone: DO_TIME_ZONE, weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)); }
export function formatDominicanDateTimeCompact(value: string | Date) { return `${formatDominicanNumericDate(value)} · ${formatDominicanTime(value)}`; }
export function formatDominicanNumericDate(value: string | Date) { return new Intl.DateTimeFormat(DO_LOCALE, { timeZone: DO_TIME_ZONE, day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)); }
export function dominicanSessionParts(value: string | Date) { const parts = new Intl.DateTimeFormat('en-US', { timeZone: DO_TIME_ZONE, day: '2-digit', month: '2-digit', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }).formatToParts(new Date(value)); const get = (type: string) => parts.find(part => part.type === type)?.value ?? ''; return { date: `${get('day')}/${get('month')}/${get('year')}`, hour: get('hour'), minute: get('minute'), period: get('dayPeriod') === 'PM' ? 'PM' : 'AM' }; }
export function dominicanFormToIso(date: string, hour: string, minute: string, period: string) { const match = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(date); if (!match) throw new Error('Escribe la fecha en formato DD/MM/AAAA.'); const [, day, month, year] = match; const twelveHour = Number(hour); if (twelveHour < 1 || twelveHour > 12) throw new Error('Selecciona una hora válida.'); const twentyFourHour = (twelveHour % 12) + (period === 'PM' ? 12 : 0); const candidate = new Date(`${year}-${month}-${day}T12:00:00-04:00`); if (Number.isNaN(candidate.getTime()) || formatDominicanNumericDate(candidate) !== `${day}/${month}/${year}`) throw new Error('La fecha indicada no es válida.'); return `${year}-${month}-${day}T${String(twentyFourHour).padStart(2, '0')}:${minute}:00-04:00`; }
